import NavBar from '@/components/NavBar';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import { AlertContextProvider } from '@/context/AlertContext';
import { AuthContextProvider } from '@/context/AuthContext';
import type { Metadata } from 'next';
import { WithAuth } from '@/components/auth/WithAuth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ThemeRegistry>
          <AuthContextProvider>
            <AlertContextProvider>
              <NavBar />
              <WithAuth>{children}</WithAuth>
            </AlertContextProvider>
          </AuthContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
