import { BasicEntity, Price, FreezerWithVensions, Freezer } from './general_types';

export const animals: BasicEntity[] = [
  {
    id: 1,
    name: 'Reh',
  },
  {
    id: 2,
    name: 'Wildschwein',
  },
];

export const meats: BasicEntity[] = [
  {
    id: 1,
    name: 'Rücken',
  },
  {
    id: 2,
    name: 'Keule',
  },
  {
    id: 3,
    name: 'Schulter',
  },
  {
    id: 4,
    name: 'Brust',
  },
];

export const freezers_only: Freezer[] = [
  {
    id: 1,
    name: 'Gefrierschrank 1',
    drawerNumbers: 10,
  },
  {
    id: 2,
    name: 'Gefrierschrank 2',
    drawerNumbers: 5,
  },
  {
    id: 3,
    name: 'Gefrierschrank 3',
    drawerNumbers: 8,
  },
];

export const freezers: FreezerWithVensions[] = [
  {
    id: 1,
    name: 'Gefrierschrank 1',
    drawerNumbers: 10,
    vensions: [
      {
        id: 1,
        freezerId: 1,
        drawerNumber: 'Nicht zugewiesen',
        animal_id: 1,
        meat_id: 2,
        weight: 380,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: '',
      },
      {
        id: 8,
        freezerId: 1,
        drawerNumber: 'Nicht zugewiesen',
        animal_id: 1,
        meat_id: 2,
        weight: 600,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 3,
        reservedFor: '',
      },
      {
        id: 9,
        freezerId: 1,
        drawerNumber: 4,
        animal_id: 2,
        meat_id: 1,
        weight: 1100,
        count: 1,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: 'Hans',
      },
      {
        id: 10,
        freezerId: 1,
        drawerNumber: 1,
        animal_id: 1,
        meat_id: 4,
        weight: 340,
        count: 3,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 2,
        reservedFor: '',
      },
      {
        id: 11,
        freezerId: 1,
        drawerNumber: 3,
        animal_id: 2,
        meat_id: 2,
        weight: 850,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 4,
        reservedFor: '',
      },
      {
        id: 12,
        freezerId: 1,
        drawerNumber: 5,
        animal_id: 1,
        meat_id: 1,
        weight: 920,
        count: 1,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 5,
        reservedFor: 'Silke',
      },
      {
        id: 13,
        freezerId: 1,
        drawerNumber: 2,
        animal_id: 2,
        meat_id: 4,
        weight: 380,
        count: 4,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 3,
        reservedFor: 'Hans',
      },
      {
        id: 14,
        freezerId: 1,
        drawerNumber: 6,
        animal_id: 1,
        meat_id: 2,
        weight: 550,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 2,
        reservedFor: '',
      },
      {
        id: 15,
        freezerId: 1,
        drawerNumber: 'Nicht zugewiesen',
        animal_id: 2,
        meat_id: 1,
        weight: 1050,
        count: 1,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: 'Silke',
      },
      {
        id: 16,
        freezerId: 1,
        drawerNumber: 4,
        animal_id: 1,
        meat_id: 4,
        weight: 310,
        count: 3,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 3,
        reservedFor: '',
      },
      {
        id: 17,
        freezerId: 1,
        drawerNumber: 1,
        animal_id: 2,
        meat_id: 2,
        weight: 820,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 2,
        reservedFor: 'Hans',
      },
      {
        id: 18,
        freezerId: 1,
        drawerNumber: 3,
        animal_id: 1,
        meat_id: 1,
        weight: 900,
        count: 1,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: 'Silke',
      },
      {
        id: 19,
        freezerId: 1,
        drawerNumber: 5,
        animal_id: 2,
        meat_id: 4,
        weight: 400,
        count: 4,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 4,
        reservedFor: '',
      },
    ],
  },
  {
    id: 2,
    name: 'Gefrierschrank 2',
    drawerNumbers: 5,
    vensions: [
      {
        id: 1,
        freezerId: 2,
        drawerNumber: 'Nicht zugewiesen',
        animal_id: 1,
        meat_id: 2,
        weight: 380,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: '',
      },
      {
        id: 8,
        freezerId: 2,
        drawerNumber: 'Nicht zugewiesen',
        animal_id: 1,
        meat_id: 2,
        weight: 600,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 3,
        reservedFor: '',
      },
      {
        id: 9,
        freezerId: 2,
        drawerNumber: 4,
        animal_id: 2,
        meat_id: 1,
        weight: 1100,
        count: 1,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 1,
        reservedFor: 'Hans',
      },
      {
        id: 10,
        freezerId: 2,
        drawerNumber: 1,
        animal_id: 1,
        meat_id: 4,
        weight: 340,
        count: 3,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 2,
        reservedFor: '',
      },
      {
        id: 11,
        freezerId: 2,
        drawerNumber: 3,
        animal_id: 2,
        meat_id: 2,
        weight: 850,
        count: 2,
        date: new Date().toISOString().split('T')[0].split('-').slice(0, 2).join('-'),
        price_id: 4,
        reservedFor: '',
      },
    ],
  },
  {
    id: 3,
    name: 'Gefrierschrank 3',
    drawerNumbers: 8,
    vensions: [],
  },
];

export const prices: Price[] = [
  {
    id: 1,
    animal_id: 1,
    meat_id: 1,
    price: 10.0,
  },
  {
    id: 2,
    animal_id: 1,
    meat_id: 2,
    price: 15.0,
  },
  {
    id: 3,
    animal_id: 2,
    meat_id: 3,
    price: 8.5,
  },
  {
    id: 4,
    animal_id: 2,
    meat_id: 4,
    price: 5.0,
  },
  {
    id: 5,
    animal_id: 1,
    meat_id: 5,
    price: 7.5,
  },
];
